openapi: "3.0.0"
info:
  title: Account API
  version: "1.0.0"

servers:
  - url: /

paths:
  /api/v1/accounts:
    post:
      summary: Create a new account
      responses:
        '200':
          description: Successfully created a new account
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    example: account
        '400':
          description: BindJSON error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: BindJSON error
        '401':
          description: Failed to create account
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: create account error
    get:
      summary: Get all accounts
      responses:
        '200':
          description: Successfully retrieved accounts
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: string
                    example: accounts
        '400':
          description: Failed to get accounts
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: get accounts error
  /api/v1/accounts/{username}:
    get:
      summary: Get account by username
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved account
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    example: account
        '400':
          description: Failed to get account
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: get account error
        '404':
          description: Account not found
    delete:
      summary: Delete an account
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted account
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    example: account
        '400':
          description: BindJSON error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: BindJSON error
        '401':
          description: Failed to delete account
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: delete account error
    put:
      summary: Update an account
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully updated account
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: string
                    example: account
        '400':
          description: BindJSON error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: BindJSON error
        '401':
          description: Failed to update account
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: update account error